FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /app

COPY /app_frontend/package*.json ./

RUN npm install

#COPY /app_frontend .

#RUN npm run build

#EXPOSE 8080
#CMD [ "http-server", "dist" ]

EXPOSE 5173
CMD ["npm", "run", "dev"]
